# 第9章 错误处理



Rust 将错误分为两个主要类别：可恢复错误和不可恢复错误。

Rust 提供了分层式错误处理方案：

`Option<T>`：用于处理有值和无值的情况。

`Result<T, E>`：用于处理可恢复错误的情况。

`Panic`：用于处理不可恢复错误的情况。

`Abort`：用于处理会发生灾难性后果的情况。用于在一些特殊场景下终止进程，退出整个程序。





## 9.1 `Result<T, E>`

Rust 中通过 `Result<T, E>` 枚举类作返回值来进行异常表达。

`Result<T, E>` 枚举包含两个值：`Ok` 和 `Err`：

```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

当 `Result` 的值为 `Ok` 时，泛型类型 `T` 作为调用成功返回的值的数据类型。当 `Result` 的值为 `Err` 时，泛型类型 `E` 作为调用失败返回的错误类型。成功返回 `T` 类型的值，失败返回 `E` 类型的值。

### 9.1.1 高效处理 `Result<T, E>`

在 Rust 标准库中，可能产生异常的函数的返回值都是 `Result<T, E>` 类型。`Result<T, E>` 类型的值的常规处理方法是使用 `match` 模式匹配。

```rust
// match 模式匹配对返回值进行相应的处理
use std::fs::File;

fn main() {
    let f = File::open("hello.txt"); // 返回值类型是 Result<T, E>
    								 // 这里 T 的类型是 std::fs::File，它是一个可以进行读写操作的文件句柄。
    								 // E 的类型是 std::io::Error，表示可能因为文件不存在或没有权限而访问失败。

    // 使用 match 模式匹配对返回值进行相应的处理：
    // 成功，f 的值是一个包含文件句柄的 Ok 实例，返回这个文件句柄并赋值给变量 file
    // 失败，f 的值是一个包含错误信息的 Err 实例，调用 panic! 终止程序并输出错误信息
    let file = match f {
        Ok(file) => file,
        Err(e) => {
            panic!("Failed to open `hello.txt`. err: {:?}", e);
        },
    };
}


/*
运行结果：

thread 'main' panicked at 'Failed to open `hello.txt`. err: Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }', main.rs:9:13
*/
```



`Result<T, E>` 类型提供的 `unwrap` 和 `expect` 方法可以实现与 `match` 模式匹配相似的功能。

```rust
// unwrap 方法处理 Result
use std::fs::File;

fn main() {
    let file = File::open("hello.txt").unwrap();
}


/*
运行结果：

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }', main.rs:4:40
*/
```

如果 `Result` 的值是 `Ok`，`unwrap` 方法会返回 `Ok` 中的值。如果 `Result` 的值是 `Err`，`unwrap` 方法会自动 `panic` 并输出默认的错误信息。



```rust
// expect 方法处理返回值结果
use std::fs::File;

fn main() {
    let file = File::open("hello.txt").expect("Sorry! Failed to open `hello.txt`.");
}


/*
运行结果：

thread 'main' panicked at 'Sorry! Failed to open `hello.txt`.: Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }', main.rs:4:40
*/
```

`expect` 方法不仅具备 `unwrap` 方法的功能，还允许自定义错误信息。



### 9.1.2 处理不同类型的错误

```rust
// match 模式匹配处理不同类型的错误
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let file = match f {
        Ok(file) => file,
        Err(error) => match error.kind() { // 这里的 error 类型是 io::Error，它是标准库提供的结构体类型。调用 kind 方法可以获得一个 io::ErrorKind 类型的值
            ErrorKind::NotFound => match File::create("hello.txt") { // 代表要打开的文件不存在时的错误
                Ok(fc) => fc,
                // 内部的 match 模式匹配语句，比如：磁盘容量不足或当前用户权限不够而导致创建文件失败
                Err(e) => panic!("Failed to create `hello.txt`, error: {:?}", e),
            },

            // 其他所有非 ErrorKind::NotFound 错误类型的处理方式
            _ => panic!("other error: {:?}", error),
        },
    };
}


/*
运行结果：

会在当前目录中创建一个 hello.txt 文件
*/
```

`io::ErrorKind` 是标准库提供的枚举类型，它的值对应 `I/O` 操作中各种可能出现的错误。



`Result` 的 `unwrap_or_else` 方法可以消除多层嵌套的 `match` 模式匹配，以简化代码：

```rust
// unwrap_or_else 方法处理不同类型的错误
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|e| {
                panic!("Failed to create `hello.txt`, e: {:?}", e);
            }) // 不要加分号 `;`，否则就是语句了，不会有返回值
        } else {
            panic!("Failed to create `hello.txt`, error: {:?}", error);
        }
    });
}


/*
运行结果：

会在当前目录中创建一个 hello.txt 文件
*/
```

如果 `Result` 的值是 `Ok`，`unwrap_or_else` 会返回 `Ok` 中的值。如果 `Result` 的值是 `Err`，`unwrap_or_else` 可以执行一个闭包。



### 9.1.3 传播错误

可以把处理错误的选择权交给该函数的调用者，调用者可能拥有更多的信息或逻辑来决定应该如何处理错误，这被称为传播错误。

```rust
// match 模式匹配传播错误
use std::fs::File;
use std::io;
use std::io::Read;

fn read_from_file() -> Result<String, io::Error> { // 如果文件不存在或读取失败，就将这些错误返回给调用者。返回值是 Result<T, E> 类型的值
    let f = File::open("hello.txt");
    let mut file = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut s = String::new();
    match file.read_to_string(&mut s) { // read_to_string 方法也返回一个 Result，所以还需要 match 模式匹配来处理。
        								// 如果执行成功，将从文件中读取的内容字符串封装在 Ok 中返回。如果执行失败，将错误返回给调用者。
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}

fn main() {
    println!("content: {}", read_from_file().unwrap());
}


/*
运行结果：


*/
```



传播错误非常常见，Rust 提供了 `?` 操作符来简化代码。`?` 操作符可以用于返回值类型为 `Result` 的函数中，它被定义为与 `match` 模式匹配有着完全相同的工作方式。

`?` 操作符与 `match` 模式匹配不同的是：`?` 操作符所使用的错误值会被传递给 `from` 函数，它定义于标准库的 `From trait` 中。`?` 操作符收到的错误类型会被转换为当前函数要返回的错误类型。

```rust
// ? 操作符的使用
use std::fs::File;
use std::io;
use std::io::Read;

fn read_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?; // 如果成功，? 操作符会把 Ok 中的值返回给变量 f。如果出现错误，? 操作符会提前返回整个函数并将 Err 值传播给调用者
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s)
}

fn main() {
    println!("content: {}", read_from_file().unwrap());
}
```



使用链式方法调用，进一步简化代码：

```rust
// ? 操作符的链式调用
use std::fs::File;
use std::io;
use std::io::Read;

fn read_from_file() -> Result<String, io::Error> {
    let mut s = String::new();
    File::open("hello.txt")?.read_to_string(&mut s)?;
    Ok(s)
}

fn main() {
    println!("content: {}", read_from_file().unwrap());
}
```

`?` 操作符的实际作用是将 `Result` 类非异常的值直接取出，如果有异常就将异常 `Result` 返回出去。





## 9.2 `Panic`

### 9.2.2 捕获 `Panic`

Rust 提供了 `panic::catch_unwind` 函数让开发者捕获 `panic`，以便程序可以继续执行而不被中止。

注意：应该避免滥用 `catch_unwind` 作为处理错误的惯用方法，因为可能会导致内存不安全。

```rust
// catch_unwind 函数捕获 panic
use std::panic;

fn main() {
    let v = vec![1, 2, 3];
    println!("{}", v[0]);
    let result = panic::catch_unwind(|| println!("{}", v[99]));
    println!("{}", result.is_err());
    println!("{}", v[1]);
}


/*
运行结果：

1
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', main.rs:6:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
true
2
*/
```

`catch_unwind` 函数接收的闭包中的代码会导致 `Panic`，但 `catch_unwind` 函数会捕获这个 `Panic` 并继续执行后面的程序。